# Generated by Django 2.2.4 on 2019-08-16 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtubevideo',
            old_name='titel',
            new_name='title',
        ),
    ]
