# Generated by Django 2.2.4 on 2019-08-18 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_auto_20190816_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='models.Project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='state',
            name='parts',
            field=models.ManyToManyField(blank=True, to='models.Part'),
        ),
    ]
