# Generated by Django 2.2.4 on 2019-08-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_auto_20190818_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeperformancemeasurement',
            name='duration',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='trackmeasurement',
            name='duration',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='trackpartmeasurement',
            name='duration',
            field=models.DurationField(),
        ),
    ]
