# Generated by Django 2.2.4 on 2019-08-18 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_fuel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='model',
        ),
    ]
