# Generated by Django 2.2.4 on 2019-08-18 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0009_remove_project_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='fuel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='models.Fuel'),
        ),
    ]
