# Generated by Django 2.2.4 on 2019-08-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0010_auto_20190818_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='model',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
