# Generated by Django 2.2.4 on 2019-08-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0011_project_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='model',
            field=models.CharField(max_length=50),
        ),
    ]
