# Generated by Django 2.2.4 on 2019-08-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0015_brand_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='image',
            field=models.ImageField(default='', max_length=200, upload_to=''),
            preserve_default=False,
        ),
    ]
