# Generated by Django 2.2.4 on 2019-09-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0016_state_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default='', max_length=200, upload_to='static/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='state',
            name='image',
            field=models.ImageField(max_length=200, upload_to='static/'),
        ),
    ]
